AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/**/*_spec.rb' 
    - 'spec/factories/**/*.rb' 

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/migrate/*.rb'
    - 'app/controllers/api/base_controller.rb' # TODO: refactor the authenticate feature

Naming/AccessorMethodName:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
