AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/**/*_spec.rb' 
    - 'spec/factories/**/*.rb' 

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'