AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'app/views/**/*.json.jbuilder'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'